package com.feng.generator.dao;

import com.feng.generator.bean.Sc;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    int deleteByPrimaryKey(@Param("sno") String sno, @Param("cno") String cno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    int insert(Sc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    Sc selectByPrimaryKey(@Param("sno") String sno, @Param("cno") String cno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    List<Sc> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    int updateByPrimaryKey(Sc record);
}