package com.feng.generator.bean;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Cno
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    private String cno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Cname
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Cpno
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    private String cpno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Ccredit
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    private Short ccredit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Cno
     *
     * @return the value of course.Cno
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Cno
     *
     * @param cno the value for course.Cno
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public void setCno(String cno) {
        this.cno = cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Cname
     *
     * @return the value of course.Cname
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Cname
     *
     * @param cname the value for course.Cname
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Cpno
     *
     * @return the value of course.Cpno
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public String getCpno() {
        return cpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Cpno
     *
     * @param cpno the value for course.Cpno
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public void setCpno(String cpno) {
        this.cpno = cpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Ccredit
     *
     * @return the value of course.Ccredit
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public Short getCcredit() {
        return ccredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Ccredit
     *
     * @param ccredit the value for course.Ccredit
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public void setCcredit(Short ccredit) {
        this.ccredit = ccredit;
    }
}