package com.feng.generator.bean;

public class Sc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.Sno
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    private String sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.Cno
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    private String cno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.Grade
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    private Short grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.Sno
     *
     * @return the value of sc.Sno
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.Sno
     *
     * @param sno the value for sc.Sno
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public void setSno(String sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.Cno
     *
     * @return the value of sc.Cno
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.Cno
     *
     * @param cno the value for sc.Cno
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public void setCno(String cno) {
        this.cno = cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.Grade
     *
     * @return the value of sc.Grade
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public Short getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.Grade
     *
     * @param grade the value for sc.Grade
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public void setGrade(Short grade) {
        this.grade = grade;
    }
}