package com.feng.generator.bean;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sno
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    private String sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sname
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Ssex
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    private String ssex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sage
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    private Short sage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sdept
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    private String sdept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sno
     *
     * @return the value of student.Sno
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sno
     *
     * @param sno the value for student.Sno
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public void setSno(String sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sname
     *
     * @return the value of student.Sname
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sname
     *
     * @param sname the value for student.Sname
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Ssex
     *
     * @return the value of student.Ssex
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public String getSsex() {
        return ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Ssex
     *
     * @param ssex the value for student.Ssex
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public void setSsex(String ssex) {
        this.ssex = ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sage
     *
     * @return the value of student.Sage
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public Short getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sage
     *
     * @param sage the value for student.Sage
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public void setSage(Short sage) {
        this.sage = sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sdept
     *
     * @return the value of student.Sdept
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public String getSdept() {
        return sdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sdept
     *
     * @param sdept the value for student.Sdept
     *
     * @mbg.generated Tue May 18 18:42:35 CST 2021
     */
    public void setSdept(String sdept) {
        this.sdept = sdept;
    }
}