package com.feng.generator.bean;

import java.util.Date;

public class Why {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column why.id
     *
     * @mbg.generated Tue May 18 09:22:23 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column why.name
     *
     * @mbg.generated Tue May 18 09:22:23 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column why.date
     *
     * @mbg.generated Tue May 18 09:22:23 CST 2021
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column why.id
     *
     * @return the value of why.id
     *
     * @mbg.generated Tue May 18 09:22:23 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column why.id
     *
     * @param id the value for why.id
     *
     * @mbg.generated Tue May 18 09:22:23 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column why.name
     *
     * @return the value of why.name
     *
     * @mbg.generated Tue May 18 09:22:23 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column why.name
     *
     * @param name the value for why.name
     *
     * @mbg.generated Tue May 18 09:22:23 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column why.date
     *
     * @return the value of why.date
     *
     * @mbg.generated Tue May 18 09:22:23 CST 2021
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column why.date
     *
     * @param date the value for why.date
     *
     * @mbg.generated Tue May 18 09:22:23 CST 2021
     */
    public void setDate(Date date) {
        this.date = date;
    }
}